#!/bin/bash
set -eu
root=$(readlink -f "$(dirname "$0")/..")
cd "$root"
eval "$(llama config -shell)"
container="$1"
path="${2-images/$container}"
scripts/build-container "$container" "$path"
aws --region "$llama_region" lambda create-function \
    --function-name "$container" --memory-size 1769 \
    --role "$llama_iam_role" \
    --environment "Variables={LLAMA_OBJECT_STORE=$llama_object_store}" \
    --timeout 60 \
    --package-type Image \
    --code "ImageUri=${llama_ecr_repository}:$container" >/dev/null
scripts/wait-for-function "$container"
