#!/bin/bash
set -eu
root=$(readlink -f "$(dirname "$0")/..")
cd "$root"
container="$1"
. scripts/_vars
scripts/build-container "$container"
repository_tag="$repository_url:$container"
status=$(aws --query Configuration.LastUpdateStatus --output text lambda update-function-code \
             --function-name "$container" \
             --image-uri "${repository_tag}")

echo "Sleeping until update is complete..."
while :; do
    case "$status" in
        Successful)
            exit 0
            ;;
        None|InProgress)
            ;;
        *)
            echo "Unexpected status: $status" >&2
            exit 1
    esac
    status=$(aws --query Configuration.LastUpdateStatus --output text lambda get-function --function-name optipng)
    sleep 1
done
