#!/bin/bash
set -eu
root=$(readlink -f "$(dirname "$0")/..")
cd "$root"
container="$1"
path="${2-images/$container}"
eval "$(llama config -shell)"
scripts/build-container "$container" "$path"
repository_tag="$llama_ecr_repository:$container"
aws --region "$llama_region" lambda update-function-code \
    --function-name "$container" \
    --image-uri "${repository_tag}" >/dev/null
scripts/wait-for-function "$container"
