#!/bin/bash
set -eu
root=$(readlink -f "$(dirname "$0")/..")
cd "$root"
container="$1"
account_id=$(aws --output text --query Account sts get-caller-identity)
repository_base="${account_id}.dkr.ecr.us-west-2.amazonaws.com"
repository_tag="$repository_base/llama:$container"

docker build -t nelhage/llama .
docker build -t "$repository_tag" "doc/$container"
if ! docker push "$repository_tag"; then
    aws ecr get-login-password | docker login --username AWS --password-stdin "$repository_base"
    docker push "$repository_tag"
fi
status=$(aws --query Configuration.LastUpdateStatus --output text lambda update-function-code \
             --function-name "$container" \
             --image-uri "${repository_tag}")

echo "Sleeping until update is complete..."
while :; do
    case "$status" in
        Successful)
            exit 0
            ;;
        None|InProgress)
            ;;
        *)
            echo "Unexpected status: $status" >&2
            exit 1
    esac
    status=$(aws --query Configuration.LastUpdateStatus --output text lambda get-function --function-name optipng)
    sleep 1
done
