#!/bin/bash
header='// Copyright 2020 Nelson Elhage
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.'
go_files=$(git ls-files -- '*.go')
fix=
if [ "$1" = "--fix" ]; then
    fix=1
fi

error=
for file in $go_files; do
    found=$(sed -En '1,/^(package|$)/p' "$file")
    if [ "$header" = "$found" ]; then
        continue
    fi
    error=1
    if [ "$fix" ]; then
        fixed=$(
            echo "$header"
            echo
            sed -En '/^(package|$)/,$ p' "$file"
             )
        echo "$fixed" > "$file"
        echo "Fixed license header: $file"
    else
        echo "Missing/incorrect license: $file"
    fi
done

if [ "$error" ]; then
    exit 1
else
    echo "All .go files contain license headers."
fi
